# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
variables:
  not_skip: true

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: "skipped"
  condition: eq(variables.not_skip, true)

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    sleep 5
    echo 'Run a one-line script'
    sleep 5
    echo 'Run a one-line script'
    sleep 5
    echo 'Run a one-line script'
    sleep 5
    echo 'Run a one-line script'
    sleep 5
    echo 'Run a one-line script'
    exit 1

  displayName: 'Run a multi-line script'
