# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  not_skip: true

pool:
  vmImage: ubuntu-latest

stages:
- stage: "stage1"
  jobs:
  - job: "job1"
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'

    - script: echo s"skipped"
      condition: eq(variables.not_skip, true)
    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
        sleep 5
        echo 'Run a one-line script'
        sleep 5
        echo 'Run a one-line script'
        sleep 5
        echo 'Run a one-line script'
        sleep 5
        echo 'Run a one-line script'
        sleep 5
        echo 'Run a one-line script'
        echo 'Run a one-line script'
        sleep 5
        echo 'Run a one-line script'
        echo 'Run a one-line script'
        sleep 5
        echo 'Run a one-line script'
        echo 'Run a one-line script'
        sleep 5
        echo 'Run a one-line script'

      displayName: 'Run a multi-line script'

- stage: "stage2"
  jobs:
  - job: "job2"
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'

    - script: echo s"skipped"
      condition: eq(variables.not_skip, true)

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
        sleep 5
        echo 'Run a one-line script'
        sleep 5
        echo 'Run a one-line script'
        sleep 5
        echo 'Run a one-line script'
        sleep 5
        echo 'Run a one-line script'
        sleep 5
        echo 'Run a one-line script'

      displayName: 'Run a multi-line script'

  - job: "job3"
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'

    - script: echo s"skipped"
      condition: eq(variables.not_skip, true)

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
        sleep 5
        echo 'Run a one-line script'
        sleep 5
        echo 'Run a one-line script'
        sleep 5
        echo 'Run a one-line script'
        sleep 5
        echo 'Run a one-line script'
        sleep 5
        echo 'Run a one-line script'

      displayName: 'Run a multi-line script'

